// ignore_for_file: unused_local_variable

import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:rideal/screens/dashboard/BottomNavigation.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'intro/Intropage.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_core/firebase_core.dart';
// Generated by flutterfire configure
import 'fcm_service.dart'; // Create this file with the code I provided
import 'meta_events_service.dart';
import 'package:upgrader/upgrader.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:device_preview/device_preview.dart';
import 'package:flutter/foundation.dart';
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  try {
    await FCMService.initialize();
  } catch (e) {
    // ignore: avoid_print
    print('Failed to initialize FCM: $e');
    print('App will continue without push notifications');
  }
  print("Background message: ${message.notification?.title}");
}
final RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
void main()async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  
  // Background message handler register karo
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  
  // Initialize FCM
  await FCMService.initialize();
  await MetaEventsService.initialize();
  await MetaEventsService.logAppActivate();
  runApp(
    DevicePreview(
      enabled: false,
      builder: (context) => const RideShareApp(),
    ),
  );
}

class RideShareApp extends StatefulWidget {
  const RideShareApp({super.key});

  @override
  State<RideShareApp> createState() => _RideShareAppState();
}

class _RideShareAppState extends State<RideShareApp> {
   @override
  void initState() {
    super.initState();
    setupFirebaseMessaging();
  }

  void setupFirebaseMessaging() async {
    // Request permission
    NotificationSettings settings = await FirebaseMessaging.instance.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );

    // Foreground notifications ke liye
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('Foreground message: ${message.notification?.title}');
      // Show local notification here if needed
    });

    // Background se app open hone par
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('Notification clicked: ${message.notification?.title}');
    });

    // Get token
    String? token = await FirebaseMessaging.instance.getToken();
    print('FCM Token: $token');
  }

  @override
  Widget build(BuildContext context) {
    
    return ScreenUtilInit(
      designSize: const Size(411, 891), // Increased base size to make UI smaller
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (_, child) {
    return MaterialApp(
      locale: DevicePreview.locale(context),
      title: 'Rideal',
      navigatorKey: navigatorKey,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
        primaryColor: const Color(0xFF0F9D58),
        colorScheme: ColorScheme.fromSwatch(
          primarySwatch: Colors.green,
        ).copyWith(
          primary: const Color(0xFF0F9D58),
          secondary: const Color(0xFF1B5E20),
        ),
        textTheme: GoogleFonts.interTextTheme(),
        appBarTheme: const AppBarTheme(
          elevation: 0,
          backgroundColor: Colors.white,
          iconTheme: IconThemeData(color: Colors.black),
          titleTextStyle: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),
        ),
        cardTheme: const CardThemeData(
          elevation: 2,
          shadowColor: Colors.black12,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(16)),
          ),
        ),
      ),
      builder: (context, child) {
        return DevicePreview.appBuilder(context, child ?? const SizedBox.shrink());
      },
      home: const SplashScreen(),
      navigatorObservers: [routeObserver],
    );
   },
  );
  }
}

// 1. Splash Screen
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    checkLoginStatus();
  }
  Future<void> checkLoginStatus() async {
  await Future.delayed(const Duration(seconds: 1));

  final prefs = await SharedPreferences.getInstance();
  final token = prefs.getString('auth_token');
  print('🔑 User Auth Token: $token'); // 👈
  if (!mounted) return;

  if (token != null && token.isNotEmpty) {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (_) => BottomNavigationLogic()),
    );
  } else {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (_) => IntroScreen()),
    );
  }
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
           child:Image(
            image: AssetImage("assets/images/logo.png"),
            fit: BoxFit.contain,
          ),    
      ),
    );   
  }
}
